Aggregate Functions
Project : E-Commerce Sales Analysis
Author  : MD Imran

--1. Total Number of Customers

select count(*) as total_customers
from customers;

--2. Total number of products

select count(*) as total_product
from products;

--3. Tota number of orders

select count(*) as total_orders
from orders;

--4. Total revenue(How much revenue has the company generated)

select sum(amount) as total_revenue
from payments
where payment_status = "Completed";

--5. Avgerage product price

select avg(price) as avg_amt
from products;

--6. Expensive Product

select max(price) as max_price
from products;

--7. Stock Availability

select sum(stock_quantity) as stock_avl
from products;

--8. Revenue by payment method

select payment_method, sum(amount) as total_amount
from payments
where payment_status = "completed"
group by payment_method
order by total_amount desc;

--9. Total order by status

select count(order_id) as total_orders, order_status
from orders
group by order_status
order by total_orders;

--10. Total Products in Each Category

select count(p.product_id) as total_product, c.category_name
from categories c
left join products p
on c.category_id = p.category_id
group by category_name
order by total_product;

--11. Revenue Generated by Category

select sum(oi.quantity*oi.unit_price) as total_price, c.category_name
from categories c
join products p
on p.category_id = c.category_id
join order_items oi
on oi.product_id = p.product_id
group by c.category_name
order by total_price;

--12. Total Sales by Brand

select p.brand, sum(oi.quantity*oi.unit_price) as total_revenue
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.brand
order by total_revenue;

--13. Highest Spending Customer

select c.first_name, sum(o.total_amount) as total_amount
from customers c
join orders o
on c.customer_id = o.customer_id
group by o.order_id
order by total_amount desc
limit 1;

--14. Most Ordered Product

select sum(oi.order_id) as total_orders, p.product_name
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_id
order by total_orders desc
limit 1;

--15. Average Spending per Customer

select c.first_name, avg(o.total_amount) AS Average_Spending
from Customers c
join Orders o
on c.customer_id=o.customer_id
group by c.customer_id,c.first_name
order by Average_Spending desc;

--End od Aggregate Functions



































